Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable